### ISSUE TITLE
Lens vs PLens

### ISSUE THREAD

**Issue by julien-truffaut** [beloglazov/couchdb-scala#1]
In [Lenses](https://github.com/beloglazov/couchdb-scala/blob/master/src/main/scala/com/ibm/couchdb/Lenses.scala#L24) you define a `Lens[CouchDoc[T], T]`, I don't know if it is useful in your project but you could make a `PLens` instead:

``` scala
def _couchDoc[A, B]: PLens[CouchDoc[A], CouchDoc[B], A, B] = 
PLens[CouchDoc[A], CouchDoc[B], A, B](_.doc)(d => cd => cd.copy(doc = d))
```

The advantage of this definition is that you can change the type of `CouchDoc` with `modify`.

**Comment by beloglazov** [comment]
Thanks Julien! I think it is useful to have the flexibility of being able to change the type of a document. I've released this change in `0.5.1`.
