### ISSUE TITLE
View with Reducer

### ISSUE THREAD

**Issue by mdemarne** [beloglazov/couchdb-scala#12]
Hi, I have a code looking like: 

```
val view = db.query.view[String, Int]("myDoc", "myView").get
```

My view is defined with a reducer (`_sum`). When I run:

```
view.reduce(false).query.run
```

Everything is fine - no error.  On the other hand, when I run it with:

```
view.reduce(true).query.run
```

There is a pickling error: 

```
[info]   upickle.Invalid$Data: data: Obj(ArrayBuffer((rows,Arr(ArrayBuffer(Obj(ArrayBuffer((key,Null), (value,Num(16140.0))))))))) msg: Key Missing: offset
```

I was just wondering how I could get the output my reduced view? Thanks!

**Comment by mdemarne** [comment]
Looks like reduce is not supported...?

**Comment by beloglazov** [comment]
I think you are right, we need to fix that.

**Comment by mdemarne** [comment]
Any idea if and when you would have time to look into that...? Just curious :)
