### ISSUE TITLE
View Query with Complex Key

### ISSUE THREAD

**Issue by yeyan** [beloglazov/couchdb-scala#14]
##### Complex key query

For views with array key is there any way to issue the following query?

intended query parameters:

```
startkey=["Tag 1"]
endkey=["Tag 1", {}]
```

URI:

```
/database/_design/view-name/_view/by-tag-view?startkey=[%22Tag%201%22]&&endkey=[%22Tag%201%22,%20{}]
```

I have tried issue the query with pure string, but the end key is serialized to a json string.

```
    xview.startKey(List("Tag 1")).endKey("[\"Tag 1\", {}]").query.attemptRun match {
      // In case of an error (left side of Either), print it
      case -\/(e) => e.printStackTrace()
      // In case of a success (right side of Either), print each object
      case \/-(a) => a.rows.foreach(x => println(x))//println(a)
    }
```

I have also tried to List with empty object, but this one simple not compile.

```
    xview.startKey(List("Tag 1")).endKey(List("Tag 1", Map())).query.attemptRun match {
      // In case of an error (left side of Either), print it
      case -\/(e) => e.printStackTrace()
      // In case of a success (right side of Either), print each object
      case \/-(a) => a.rows.foreach(x => println(x))//println(a)
    }
```

Is there anyway to issue a query with raw strings with couchdb-scala API?

**Comment by beloglazov** [comment]
Could you please try `xview.startKey(("Tag 1")).endKey(("Tag 1", Map()))`, i.e., using tuples instead of lists? I haven't tried it myself, please let me know if it doesn't work.

**Comment by ermyas** [comment]
@beloglazov's suggestion for using Tuples should work with slight modifications, either providing type parameter to the Map (wouldn't compile otherwise) or just using a Unit type for the second element in the tuple of endKey
- `xview.startKey(Tuple1("Tag 1")).endKey(Tuple2("Tag 1", Map[String, Int]())).query`
- `xview.startKey(Tuple1("Tag 1")).endKey(Tuple2("Tag 1", {})).query`
