### ISSUE TITLE
Getting partial results with docs.getMany

### ISSUE THREAD

**Issue by MartinKanters** [beloglazov/couchdb-scala#15]
When using docs.getMany I would like to get all the documents back which are present in the database, instead of getting a upickle.Invalid$Data error.
So if I would try to get documents by key (1, 2 and 100) where 1 and 2 are in the database, and 100 is not, I would want to get the 1 and 2 back and maybe an error for the 100. 

To me a possible solution would be to get a result back from the getMany function which would be a Map consisting of keys (of the documents), and the value would then be a Try (consisting of either a Success containing the document or a Failure containing the invalid$Data or preferably a 404 error of some sort.)

Is that possible? Or is it maybe already there but have I missed it?

**Comment by beloglazov** [comment]
It's definitely reasonable to have a way to get only the available documents, this is not supported right now however. One way could be to add something like `getManyAllowMissing[D: R](ids: Seq[String]): Task[CouchDocs[String, Option[CouchDocRev], Option[D]]]` -- basically making values of the result set optional. This would probably require adding a custom upickle `Reader` to support the `Option` type. I'd need to investigate it more and experiment to provide more details. If you implement this, I'd be happy to merge your PR in.

**Comment by ermyas** [comment]
I am running into the same problem. @beloglazov your suggestion sounds like a good way to handle this.
