### ISSUE TITLE
Additional query support for type based retrieval of Docs

### ISSUE THREAD

**Issue by ermyas** [beloglazov/couchdb-scala#41]
Currently the following operations are not supported by the documents builder api
- Fetch documents by type, given a set of ids, while allowing for missing docs
  `doc.getMany.byTypeUsingTemporaryView[FixPerson].withIds(Seq(...)).allowMissing.build.query`
- Fetching documents by type excluding documents
  `docs.getMany.byTypeUsingTemporaryView[FixPerson].excludeDocs.build.query` 
- Fetching documents by type, excluding documents while allowing for missing docs
  `docs.getMany.byTypeUsingTemporaryView[FixPerson].withIds(Seq(...)).allowMissing.excludeDocs.build.query`

These capabilities should probably be built in the new API as in the examples above than the deprecated `queryXX` APIs

**Comment by beloglazov** [comment]
👍

**Comment by ermyas** [comment]
- Points 1 and 3, unlike the Documents API AllowMissing does not appear to be a special condition that requires handling here since unknown ids to the view API are ignored
- Point 2 addressed by PR #46
