### ISSUE TITLE
Tests fail when upgrading to upickle 0.4.0

### ISSUE THREAD

**Issue by ermyas** [beloglazov/couchdb-scala#54]
All tests that use a set of keys in QueryTemporaryViewSpec fail when upgrading to upickle 0.4.0

**Comment by beloglazov** [comment]
Looks like our custom `Writer` for `ViewWithKeys` stops getting picked up by upickle after the upgrade. Another thing I noticed is that we don't have enough tests for `UpickleImplicits`, which is why it was a bit hard to find what's going wrong. I don't yet have a solution.
