### ISSUE TITLE
I can't get connection with couchdb.

### ISSUE THREAD

**Issue by JoshuaMx** [beloglazov/couchdb-scala#59]
I could make run the Basic.scala example but it doesn't make anything it show me success when I run it with the console (SBT) and when I run it with eclipse but it doesn't show any connection error or something like that, So I tried to figure out what the cause of the problen, seeing the configuration but the configuration it's so easy it's very simillar a simple JDBC, so I made a little example with java and I could get connection with the data base and I saw that, because I put the debug level in debug and I verified the data base was created and the files.
# So I don't know if you have any idea of what's going on because it doesn't throw any exception.

> run-main com.ibm.couchdb.examples.Basic
> [info] scalastyle using config /home/fidelity/workspace_6/couchdb-scala-master/scalastyle-config.xml
> [info] Processed 22 file(s)
> [info] Found 0 errors
> [info] Found 0 warnings
> [info] Found 0 infos
> [info] Finished in 2 ms
> [success] created output: /home/fidelity/workspace_6/couchdb-scala-master/target
> [info] Running com.ibm.couchdb.examples.Basic 
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [success] Total time: 1 s, completed 06-jun-2016 14:52:25

**Comment by ermyas** [comment]
thanks @JoshuaMx for reporting this. PR #61 should fix this
