### ISSUE TITLE
Unit tests with CouchDB

### ISSUE THREAD

**Issue by mb720** [beloglazov/couchdb-scala#64]
Thanks a lot for your great library!

In production, I use the official [CouchDB Docker image](https://store.docker.com/images/263ad544-d7c7-4892-8244-fe78b6231265) and I can connect to it with CouchDB-Scala just fine.

For my unit tests, I'd like to create an instance of CouchDB programmatically, without Docker. Can I do that with CouchDB-Scala?

If that's not possible, can you recommend a way to run unit tests involving CouchDB in a Scala application?

Thanks a lot in advance!

**Comment by ermyas** [comment]
Hi @mb720 thanks for your comment.
Couchdb-scala doesn't currently provide the capability to mock a Couchdb server for testing purposes. Hence, you would need to either test against a real instance of couchdb or mock appropriate couchdb-scala classes for testing.
