### ISSUE TITLE
Views and keys (documentation issue)

### ISSUE THREAD

**Issue by mb720** [beloglazov/couchdb-scala#65]
Hi!

From the readme: 

> It's also possible to only get the documents from a view that match the specified keys. For example, we can use that to get only documents of Alice and Carl:
> 
> `ageView.build.query(Seq("Alice", "Carl"))`

From the [QueryViewSpec](https://github.com/beloglazov/couchdb-scala/blob/master/src/test/scala/com/ibm/couchdb/api/QueryViewSpec.scala) I can see that this is not accurate. 

It seems that keys can be used by either[ `withIds`](https://github.com/beloglazov/couchdb-scala/blob/master/src/test/scala/com/ibm/couchdb/api/QueryViewSpec.scala#L139) or using [`keys`](https://github.com/beloglazov/couchdb-scala/blob/master/src/test/scala/com/ibm/couchdb/api/QueryViewSpec.scala#L113).

**Comment by ermyas** [comment]
thanks for pointing this out @mb720
