### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mrmechko** [beloglazov/couchdb-scala#9]
A bunch of the dependencies in the project are out of date, in particular, `upickle`.  The current version has a slightly different api, making it impossible to use `couchdb-scala` in conjunction with the latest, safest `upickle`.  I found a way to make things work in my fork [mrmechko/couchdb-scala](https://github.com/mrmechko/couchdb-scala), but I had to disable some of the `scalac` options in order for it to compile, tests work though.  I'd like to figure out exactly how to get it working with upickle 0.3.4 AND get it to compile without cheating :D

**Comment by beloglazov** [comment]
Sorry for the slow response, I'll try to take a look at your fork on the weekend :)
